- name: Setup Raspberry Pi Controllers
  hosts: controllers
  become: True
  
  tasks:
    - name: Install APT packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - "vim"
        - "isc-dhcp-server"

    - name: Copy DHCP config to Controller
      template:
        src: "templates/dhcp.conf.j2"
        dest: "/etc/dhcp/dhcpd.conf"

    - name: Start and enable DHCP service
      systemd:
        name: "isc-dhcp-server"
        state: restarted
        enabled: True
        
